### ISSUE TITLE
picgo@2.2.1: download via aria2 failed

### ISSUE THREAD

**Issue by a347807131** [helbing/scoop-bucket#1]
ERROR Download failed! (Error 22) HTTP response header was bad or unexpected
ERROR https://github.com/Molunerfinn/PicGo/releases/download/v2.2.1/PicGo-Setup-2.2.1.exe
    referer=https://github.com/Molunerfinn/PicGo/releases/download/v2.2.1/
    dir=C:\Users\Administrator\scoop\cache
    out=picgo#2.2.1#https_github.com_Molunerfinn_PicGo_releases_download_v2.2.1_PicGo-Setup-2.2.1.exe

ERROR & 'C:\Users\Administrator\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Administrator\scoop\cache\picgo.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=3788 --continue

**Comment by FDUZS** [comment]
启用 aria2 经常出问题的，我遇到过不止一次。建议 `scoop config aria2-enabled false` 将其关闭。

**Comment by a347807131** [comment]
> 启用 aria2 经常出问题的，我遇到过不止一次。建议 `scoop config aria2-enabled false` 将其关闭。

ok thanks

**Comment by a347807131** [comment]
另外，我自己的解决方案时首当下载setup包，让后放在scoop下的cache里，并改名，就能安装。
